name: CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v0.**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com/
          scope: '@owneraio'

      - name: finp2p-client install dependencies
        working-directory: ./finp2p-client
        run: npm clean-install

      - name: finp2p-client build
        working-directory: ./finp2p-client
        run: npm run build

        # ----------------------------------

      - name: finp2p-adapter-models install dependencies
        working-directory: ./finp2p-adapter-models
        run: npm clean-install

      - name: finp2p-adapter-models build
        working-directory: ./finp2p-adapter-models
        run: npm run build

        # ----------------------------------

      - name: adapter-tests install dependencies
        working-directory: ./adapter-tests
        run: npm clean-install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: adapter-tests build
        working-directory: ./adapter-tests
        run: npm run build

        # ----------------------------------

      - name: skeleton install dependencies
        working-directory: ./skeleton
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: skeleton build
        working-directory: ./skeleton
        run: npm run build

      - name: install skeleton migration tool
        working-directory: ./skeleton
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@v3.26.0
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: skeleton test
        working-directory: ./skeleton
        run: npm run test

        # ----------------------------------

      - name: sample-adapter install dependencies
        working-directory: ./sample-adapter
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: sample-adapter build
        working-directory: ./sample-adapter
        run: npm run build

      - name: sample-adapter test
        working-directory: ./sample-adapter
        run: npm test
